package com.rea.mbg.mapper.app;

import com.rea.mbg.model.app.AppUser;
import com.rea.mbg.model.app.AppUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    long countByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int deleteByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int insert(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int insertSelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    List<AppUser> selectByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    AppUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") AppUser record, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int updateByExample(@Param("record") AppUser record, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int updateByPrimaryKeySelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    int updateByPrimaryKey(AppUser record);
}