package com.tidever.mbg.model.app;

import java.io.Serializable;
import java.util.Date;

public class AppUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.user_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.app_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.color
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.date
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_id
     *
     * @return the value of app_user.user_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_id
     *
     * @param userId the value for app_user.user_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.app_id
     *
     * @return the value of app_user.app_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.app_id
     *
     * @param appId the value for app_user.app_id
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.color
     *
     * @return the value of app_user.color
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.color
     *
     * @param color the value for app_user.color
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.date
     *
     * @return the value of app_user.date
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.date
     *
     * @param date the value for app_user.date
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Dec 02 17:48:19 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", appId=").append(appId);
        sb.append(", color=").append(color);
        sb.append(", date=").append(date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}